[숫자 야구 게임] 방예혁 미션 제출합니다.
gdsc-skhu-pair-mission/java-baseball-6 pull request #10
Opened 2024-03-31 17:02 UTC by YehyeokBang

## 질문
- `View`의 책임을 결정하는 것이 어려웠습니다. 
예시1) `InputView`에서 입력을 받고 검증까지 해야하는지? 저희는 Number 객체를 생성할 때 검증하도록 구현했습니다.
예시2) 스트라이크와 볼 결과를 출력할 때 `OutputView`에게 스트라이크와 볼 개수를 주고 메시지를 만들게 하는 것이 괜찮은지? 아니라면 어디선가 완성된 문자열을 전달해야하는지? 등
- 컴퓨터 숫자(난수)를 만들 때 정적 메서드를 사용하는건 어떤지? 그 객체가 값을 가지고 있는 것은 아니고 난수를 만들고 반환만 한다면 정적 메서드도 좋은가요? 정적 메서드는 어떨 때 사용하는지가 궁금해요.
- 아래의 코드처럼 객체를 생성할 때 new 키워드를 사용해서 객체를 주입하는 방식은 안좋아보이는데 다른 방법이 있나요? 사실 좋은 방법인지 아닌지도 잘 모르겠습니다.
```java
public class BaseballGameController {

    private final InputView inputView;
    private final OutputView outputView;
    private final Computer computer;

    public BaseballGameController() {
        this.inputView = new InputView();
        this.outputView = new OutputView();
        this.computer = new Computer();
    }
    
    ...
}
``` 

## 기타
- 페어와 일정이 안맞아서 3시간만에 구현하다보니 부족한 점이 많을 것 같습니다...!

2024-04-01 08:18 UTC, hangillee requested changes
안녕하세요, 예혁! 👋

시간도 모자라고 바쁜 와중에 미션 하느라 고생하셨습니다. 그래도 이번 미션을 한 번 경험해봤던 덕분인지 훌륭하게 요구사항을 충족하신 것 같습니다!

남겨주신 질문에 대한 답변입니다!
> View의 책임을 결정하는 것이 어려웠습니다.

예혁이 생각하는 `View`의 책임은 무엇인가요? 저는 `View`는 사용자와 프로그램의 소통을 위한 인터페이스라고 생각합니다. 사용자의 입력값을 `View`에서 검증하는 것도 자연스럽고, 해당 값을 통해 객체를 생성하는 부분에서 검증하는 것도 자연스럽다고 생각합니다.

다만, `Model`은 웬만해서는 `View`로부터 넘어온 값과 분리되어야 합니다. 즉, `View`의 수정에 `Model`이 영향을 받으면 안 된다는 의미입니다. 또한, 출력 메시지도 값만 넘겨받고 `View`가 만들게 하는게 더 낫습니다. 앞서 설명한대로 `View`의 변경이 다른 계층까지 전이되어서는 안 되니까요!

> 컴퓨터 숫자(난수)를 만들 때 정적 메서드를 사용하는건 어떤지? 그 객체가 값을 가지고 있는 것은 아니고 난수를 만들고 반환만 한다면 정적 메서드도 좋은가요? 정적 메서드는 어떨 때 사용하는지가 궁금해요.

정적 메소드는 클래스 로드와 동시에 메모리에 올라가기 때문에 클래스를 인스턴스화 하지 않아도 사용 가능합니다. 즉, 인스턴스화 하지 않아도 모든 클래스에서 접근 가능하기 때문에 오용될 가능성이 높아집니다. 그래서 정적 메소드는 다른 객체와 협력하기 보단 스스로 기능을 제공하는 유틸 클래스에서 사용됩니다. `Math` 클래스가 대표적이죠.

정적 메소드의 장단은 명확하기 때문에 예혁의 판단하에 필요하다면 사용해도 좋습니다. 다만, 단점이 무엇이고 그로 인해 발생하는 문제가 무엇인지만 잘 알고 있다는 전제하에 사용해야 합니다.

> 아래의 코드처럼 객체를 생성할 때 new 키워드를 사용해서 객체를 주입하는 방식은 안좋아보이는데 다른 방법이 있나요? 사실 좋은 방법인지 아닌지도 잘 모르겠습니다.

객체를 생성하는 방식은 개발자가 결정하기 나름입니다. 사실 지금 Controller 코드는 다형성을 사용했을 때 마땅히 이점을 얻을만한 객체도 안 보이고 외부에서 의존성 주입을 할만한 코드도 보이지 않습니다. (오히려 `main` 메소드에서 `View`와 `Model`을 아는 게 더 이상해 보입니다.) 한가지 개선점을 찾자면, 굳이 생성자에서 `new`를 통해 인스턴스화 할 이유가 없다는 것입니다. 그냥 필드에 바로 `new` 해주면 안되나요? 어차피 결과는 같습니다!

테스트 코드도 추가로 작성하고 여러모로 미션을 잘 수행해주셔서 감사합니다! 코멘트 남겨드린 부분만 리팩토링 해봅시다! 힌트를 드리자면, 메소드 이름만 보고도 어떤 역할을 하는지 알 수 있어야 합니다. 흔히, **축약 금지**라고 불리는 규칙입니다. 역할과 책임도 한 번 재고해봅시다!

2024-04-01 08:18 UTC, hangillee commented on docs/README.md
> +    - [x]  종료
기능 구현 목록 작성 👍

2024-04-01 08:18 UTC, hangillee commented on src/main/java/baseball/controller/BaseballGameController.java
> +            outputView.printResultMessage(result.strike(), result.ball());
DTO를 활용하셨네요! DTO가 필요한 이유가 무엇인가요? 그냥 `model` 계층의 객체들에게서 바로 값을 가져오면 안 되나요? 🤔

2024-04-01 08:18 UTC, hangillee commented on src/main/java/baseball/controller/BaseballGameController.java
> +                break;
`early return`을 활용해봅시다.
차라리 `break`가 먼저 호출 되었다면 `if`문의 `indent`(들여쓰기)가 한 단계여도 되지 않았을까요?

2024-04-01 08:18 UTC, hangillee commented on src/main/java/baseball/controller/BaseballGameController.java
> +        this.computer = new Computer();
저는 문제 없어 보입니다. 다형성을 위해 의존성 주입을 활용한다면 모르겠으나, 지금 당장은 해당 객체들의 다형성을 활용해야할 마땅한 이유가 없어 보입니다. 오히려, `InputView`와 `OutputView`를 `static` 메소드만 가지도록 만들어 Util 클래스로 바꾸면 `BaseballGameController`가 가질 상태의 개수도 줄어들 것 같습니다.

2024-04-01 08:18 UTC, hangillee commented on src/main/java/baseball/controller/BaseballGameController.java
> +    }
이 친구들은 Controller가 가져야 할 책임일까요? 비즈니스 로직에 가까워 보이는데 오히려 도메인이 가져야 할 친구들 아닐까요? Controller의 역할과 책임의 범위는 무엇일까요? 예혁이 생각하는 Controller의 역할과 책임에 대해서 알려주세요!

또, 예혁이 고민한 대로 이 친구를 분리해주세요! (힌트를 드리자면 Computer가 가지는 것도 나쁘지 않아 보여요.)

2024-04-01 08:18 UTC, hangillee commented on src/main/java/baseball/dto/Result.java
> +}
`record` 활용 👍

2024-04-01 08:18 UTC, hangillee commented on src/main/java/baseball/model/Computer.java
> +        while (computer.size() < 3) {
매직 넘버를 상수화 해볼까요?

2024-04-01 08:18 UTC, hangillee commented on src/main/java/baseball/model/Computer.java
> +            }
메소드로 분리할 수 있을 것 같아요. 그렇게 하면 들여쓰기 단계도 줄일 수 있고, 메소드 이름만 보고, 자세한 조건과 동작을 모르고도 어떤 값들이 리스트에 추가될 지 유추할 수 있도록 리팩토링 해주세요!

2024-04-01 08:18 UTC, hangillee commented on src/main/java/baseball/model/Computer.java
> +    public void generateRandomNumber() {
이 친구를 정적 메소드로 만들었을 때 얻는 이점이 무엇이라고 생각하시나요? Computer 객체가 유틸 클래스가 아닌 이상, 정적 메소드로 만들어야 할 이유가 있을까요?

2024-04-01 08:18 UTC, hangillee commented on src/main/java/baseball/model/Number.java
> +        }
각 `if`문들을 메소드로 분리하여 메소드 이름을 통해 의미를 부여해주세요. 그렇게되면 `validation` 메소드를 대강 훑어 보더라도 어떤 내용들을 검증하는지 화인할 수 있을거에요!

2024-04-01 08:18 UTC, hangillee commented on src/main/java/baseball/model/Number.java
> +            }
정규식을 활용한다면...? `Stream`도 활용해볼 수 있을 것 같네요! 😁

2024-04-01 08:18 UTC, hangillee commented on src/main/java/baseball/model/Number.java
> +        Set<Character> set = new HashSet<>();
컬렉션의 특징을 활용한 중복 제거 👍

2024-04-01 08:18 UTC, hangillee commented on src/main/java/baseball/view/InputView.java
> +        return new Number(input);
`View`가 `Model` 패키지의 객체를 참조하게 되었네요. MVC 패턴으로 나눈 이유가 사라진 것 같아요. 리팩토링 해봅시다!

2024-04-01 08:18 UTC, hangillee commented on src/main/java/baseball/view/OutputView.java
> +            }
이 친구를 가장 상위로 올리고 `return` 해버리면 아래의 조건들은 참조할 필요도 없지 않을까요?

2024-04-01 08:18 UTC, hangillee commented on src/main/java/baseball/view/OutputView.java
> +}
EOL에 대해서 학습해봅시다!

2024-04-01 08:18 UTC, hangillee commented on src/test/java/baseball/ApplicationTest.java
> +
테스트 작성 👍

2024-04-01 08:45 UTC, YehyeokBang commented on src/main/java/baseball/controller/BaseballGameController.java
> +            outputView.printResultMessage(result.strike(), result.ball());
DTO를 사용하여 필요한 데이터(`strike`와 `ball`)를 한 번에 전달하여 코드 간결하게(불필요한 메서드 호출 감소) 만들기 위해 사용했습니다!

2024-04-01 08:49 UTC, YehyeokBang commented on src/main/java/baseball/model/Computer.java
> +    public void generateRandomNumber() {
`Computer` 객체 생성 없이 `Computer.generateRandomNumber()` 처럼 간편하게 호출이 가능하기 때문에 코드가 간결해지고 정적 메소드는 객체마다 생성되지 않고 클래스에 속하기 때문에 메모리 사용량을 줄일 수 있을 것 같습니다. 특히, `Computer` 객체가 단순히 `generateRandomNumber()` 메소드만 제공하는 경우에는 메모리 효율성 향상 효과가 더 클 것 같습니다.

2024-04-01 08:49 UTC, YehyeokBang commented on src/main/java/baseball/model/Number.java
> +            }
정규식을 활용하면 개발자가 더 읽기 좋은 코드가 될 것 같습니다.

2024-04-02 06:25 UTC, hangillee commented on src/main/java/baseball/controller/BaseballGameController.java
> +            outputView.printResultMessage(result.strike(), result.ball());
DTO는 여러 데이터를 한 번에 넘기는데 유용한 점도 있지만, 가장 중요한 장점은 핵심 비즈니스 로직이나 민감한 정보를 담고 있는 Domain을 다른 계층으로부터 완전히 분리시킬 수 있다는 점입니다! 👍

2024-04-02 06:28 UTC, hangillee commented on src/main/java/baseball/model/Computer.java
> +    public void generateRandomNumber() {
반대로 숫자 야구 게임의 규모가 커져서 여러 숫자 야구 게임 방이 생기고 참가자가 많아지면 프로그램이 종료될 때까지 `Computer.generateRandomNumber()`가 메모리에서 사라지지 않고 자리를 축내고 있을 가능성이 높지 않을까요?

`static`을 사용한다고 해서 메모리 효율성 효과가 더 클 것 같진 않아요. 심지어, 여러 사람이 동시에 숫자 야구를 플레이하게 될 경우에는 동시성 문제도 발생할 수 있을 것 같아요. GC의 대상도 되지 않을테니 메모리 누수의 위험도 있습니다!

2024-04-02 07:19 UTC, YehyeokBang commented on src/main/java/baseball/controller/BaseballGameController.java
> +                break;
넵 수정해보겠습니다!

2024-04-02 07:21 UTC, YehyeokBang commented on src/main/java/baseball/model/Computer.java
> +    public void generateRandomNumber() {
여러 방면을 생각하게 되네요 감사합니다!

2024-04-03 06:52 UTC, hangillee requested changes
리팩토링 수고하셨습니다!
조금만 더 수정하면 될 것 같아서 코멘트 남깁니다.

이번 리뷰는 같이 진행할 필요는 없습니다.

2024-04-03 06:52 UTC, hangillee commented on src/main/java/baseball/constant/GameRule.java
> +
공백 라인을 둔 특별한 이유가 있나요?

2024-04-03 06:52 UTC, hangillee commented on src/main/java/baseball/constant/GameRule.java
> +public class GameRule {
`private` 생성자를 추가해주세요! 인스턴스화를 막아야 할 것 같습니다!

2024-04-03 06:52 UTC, hangillee commented on src/main/java/baseball/constant/ViewMessage.java
> +public class ViewMessage {
마찬가지로 `private` 생성자를 선언해주세요!

2024-04-03 06:52 UTC, hangillee commented on src/main/java/baseball/controller/BaseballGameController.java
> +    }
코드를 조금만 바꾼다면 `indent`가 1로 줄어들 것 같습니다!

힌트) `inputView.isRestart()`의 반환값을 변수에 받아온다면...?

2024-04-03 06:52 UTC, hangillee commented on src/main/java/baseball/controller/BaseballGameController.java
> +        }
이 친구도 마찬가지로 `indent`를 1로 줄일 수 있을 것 같아요. 리팩토링 해봅시다.

2024-04-03 06:52 UTC, hangillee commented on src/main/java/baseball/dto/Result.java
> +    }
DTO에 비즈니스 로직에 두는 것은 위험할 수도 있습니다! 지금은 간단하지만 더 많은 로직이 생길 경우 문제가 생길 여지가 있습니다. DTO가 다양한 도메인에서 사용될 때, 다른 개발자가 로직을 오용하기 쉬울 수 있고, 의존하는 도메인이 많아질 수록 해당 로직을 변경하는데 부담이 커집니다. 해당 로직을 다른 객체에 적절하게 위임해봅시다!

2024-04-03 06:52 UTC, hangillee commented on src/main/java/baseball/constant/ViewMessage.java
> +public class ViewMessage {
`Enum`을 활용해볼 수도 있을 것 같아요!

2024-04-03 06:52 UTC, hangillee commented on src/main/java/baseball/model/Computer.java
> +        while (uniqueNumbers.size() < 3) {
매직 넘버 `3`대신 `NUMBERS_SIZE`를 사용하는 건 어떨까요?

2024-04-03 06:52 UTC, hangillee commented on src/main/java/baseball/model/Computer.java
> +import static baseball.constant.GameRule.NUMBERS_SIZE;
`Enum`이나 상수에 대한 `static import`에 대해 코드의 가독성을 저해시키는 요인 중 하나라는 의견이 있습니다. `static import`를 하지 않는 것을 추천드립니다.

2024-04-03 06:52 UTC, hangillee commented on src/main/java/baseball/model/Computer.java
> +    // Set 자료구조를 사용해 중복되는 수의 개수를 반환하는 메서드
주석 없어도 충분히 이해가게 잘 작성해주셨어요! 지워주시면 좋을 것 같습니다.

2024-04-03 06:52 UTC, hangillee commented on src/main/java/baseball/model/Computer.java
> +        set.addAll(list2);
컬렉션을 적극 활용하는 코드 👍

2024-04-03 06:52 UTC, hangillee commented on src/main/java/baseball/model/Numbers.java
> +        set = null;
GC가 처리하도록 신경쓰지 않아도 될 것 같아요. 이 정도는 메모리에 크게 영향은 가지 않습니다. 이전 피드백 때문에 해두신 건 이해하지만 굳이 필요한 코드는 아닌 것 같습니다. 오히려 주석이 없으면 의도를 이해하기 힘든 코드라 컨벤션으로 정한게 아닌 이상 다른 개발자가 코드를 이해하는데 방해가 될 수 있습니다.

2024-04-03 06:52 UTC, hangillee commented on src/main/java/baseball/model/Numbers.java
> +                .collect(Collectors.toList());
그냥 `.toList()`로 사용할 수 있습니다!

2024-04-03 07:44 UTC, YehyeokBang reviewed
감사합니다. 더 고민해보겠습니다.

2024-04-03 07:44 UTC, YehyeokBang commented on src/main/java/baseball/constant/GameRule.java
> +
위 3개는 사용자가 게임 내에 사용하는 숫자(범위, 개수)와 관련되었고, 아래는 게임 재시작과 관련된 값이라서 고민하다가 띄워두었습니다.

2024-04-03 07:44 UTC, YehyeokBang commented on src/main/java/baseball/constant/ViewMessage.java
> +public class ViewMessage {
넵

2024-04-03 07:44 UTC, YehyeokBang commented on src/main/java/baseball/constant/ViewMessage.java
> +public class ViewMessage {
처음에는 `Enum`을 사용해서 만들었는데, `Enum`도 객체이기 때문에 선언된 값(문자열, 정수 등)을 사용하려면 아래처럼 메서드 하나를 더 써야했습니다. 제가 구현한 코드에서는 `Enum`을 사용해서 얻는 이점보다 깔끔하게 보이는 것이 더 좋다고 생각해서 이렇게 구현했습니다. 현재 코드에서 `Enum` 사용했을 때의 이점이 무엇이 있는지 궁금합니다..! 또한 이렇게 간단한 구현에서 비교 후 선택한 제 행동이 괜찮은 접근인지 궁금합니다!
```java
// Enum 사용
String msg = ViewMessage.GAME_START.getMessage();

// 현재
String msg = ViewMessage.GAME_START;
```

2024-04-03 07:44 UTC, YehyeokBang commented on src/main/java/baseball/controller/BaseballGameController.java
> +    }
고민해보겠습니다!

2024-04-03 07:44 UTC, YehyeokBang commented on src/main/java/baseball/dto/Result.java
> +    }
넵!

2024-04-03 07:44 UTC, YehyeokBang commented on src/main/java/baseball/model/Numbers.java
> +                .collect(Collectors.toList());
변경될 이유가 없으니 불변 리스트로 반환하는 것이 더 좋겠네요 감사합니다!

2024-04-04 06:15 UTC, hangillee approved these changes
안녕하세요, 예혁! 👋

피드백 잘 반영해주셨네요. 몇 가지만 더 신경쓰면 좋을 것 같습니다. POSIX New Line에 대해서 학습해보고 다음 미션부터는 신경써주세요! merge하도록 하겠습니다!

자동차 경주 미션도 파이팅!

2024-04-04 06:15 UTC, hangillee commented on src/main/java/baseball/constant/ViewMessage.java
> +public class ViewMessage {
`Enum`을 사용하면 `Enum` 자체에 로직을 두어 스스로 어떤 로직을 처리하게 둘 수도 있습니다. 또, `values()` 메소드를 활용해 `Enum`의 구체적인 값을 모르고도 로직을 처리하는 방법도 있습니다. 자세한 내용은 제 체스 게임 repository의 `Enum`들을 확인해보시면 됩니다!

2024-04-04 06:15 UTC, hangillee commented on src/main/java/baseball/constant/ViewMessage.java
> +public class ViewMessage {
물론, 예혁의 이런 접근도 전 괜찮다고 생각합니다. 당장에 `ViewMessage` 객체는 자체적으로 수행할 로직이 없어 보이니 이대로 둬도 무방할 것 같습니다.

확고한 자신만의 기준 👍

2024-04-04 06:15 UTC, hangillee commented on src/main/java/baseball/constant/GameRule.java
`GameRule`은 `model` 패키지에, `ViewMessage`는 `view` 패키지로 이동하는게 좋아보여요. 패키지 의존성도 중요합니다.

2024-04-04 06:15 UTC, merged