[숫자 야구 게임] 박소정 미션 제출합니다.
gdsc-skhu-pair-mission/java-baseball-6 pull request #11
Opened 2024-03-31 17:18 UTC by sojeong0202

### :boom: 어려웠던 점
- 언니랑 해서 전보다 수월하게 풀었는데, 과연 혼자 했다면 풀 수 있었을까 싶습니다.
- 상대방에게 내 머릿속 코드(생각)를 잘 설명하기 힘들었다. 어떻게 하면 설명을 잘 할 수 있을까요?

### :monocle_face: 궁금한 점
- 
<img width="518" alt="image" src="https://github.com/gdsc-skhu-pair-mission/java-baseball-6/assets/112674378/ff268645-2139-4619-9c89-02886259734c">

이 주의 표시가 의미하는 바를 잘 모르겠습니다.
Alt + Enter를 눌러도 뭔가 고치는 느낌이 안 들고 뭐지...?  이런 생각밖에 안 드는데 도대체 뭘까요?
![image](https://github.com/gdsc-skhu-pair-mission/java-baseball-6/assets/112674378/e6f132a6-bc78-4786-aa77-40dfa539aa23)

- 
<img width="575" alt="image" src="https://github.com/gdsc-skhu-pair-mission/java-baseball-6/assets/112674378/f5e074ba-50c8-40b9-9421-08f64867e495"> 

![image](https://github.com/gdsc-skhu-pair-mission/java-baseball-6/assets/112674378/f24d77d8-3394-4231-81e0-903f75afed81)

스트림에서 왜 [클래스 이름::메서드 이름] 이렇게 나타내는지 모르겠어요. [클래스 이름.메서드 이름] 이렇게 나타내면 되지 않나 싶은데... 이유가 있으니 이렇게 하는 거겠죠? 찾아봤는데 안 나오더라고요. (~~제대로 안 찾은 건가..~~.)

2024-04-01 08:52 UTC, hangillee requested changes
안녕하세요, 소정! 👋

한번 해본 미션이지만 페어 프로그래밍이라는 익숙치 않은 방식으로 해결하느라 고생 많았습니다! 전반적으로 완성도 높은 코드였습니다. 느낀 점과 배운 점 적어주신 것도 인상 깊었어요!

남겨주신 질문에 대한 답변입니다!
> 상대방에게 내 머릿속 코드(생각)를 잘 설명하기 힘들었다. 어떻게 하면 설명을 잘 할 수 있을까요?

그래서 중요한게 코드 컨벤션입니다. 함께 합의한 코드 컨벤션이 잘 지켜졌다는 가정 하에 읽기 쉬운 코드(클린 코드)가 완성되었다면 당연히 코드만 읽고도 서로가 어떤 의도를 가졌는지 파악하기 쉽습니다.

> 이 주의 표시가 의미하는 바를 잘 모르겠습니다. Alt + Enter를 눌러도 뭔가 고치는 느낌이 안 들고 뭐지...? 이런 생각밖에 안 드는데 도대체 뭘까요?

코멘트로 남겼습니다!

> 스트림에서 왜 [클래스 이름::메서드 이름] 이렇게 나타내는지 모르겠어요. [클래스 이름.메서드 이름] 이렇게 나타내면 되지 않나 싶은데... 이유가 있으니 이렇게 하는 거겠죠? 찾아봤는데 안 나오더라고요. (제대로 안 찾은 건가...)

Java Lambda 메소드 참조로 구글링 해보세요! `::`은 연산자로, `Stream`을 통해 넘어오는 각 `Stream` 요소들을 `::`을 통해 호출한 메소드의 매개변수로 **자동**으로 넘겨줍니다. 즉, Java의 연산자이며 `.`(도트) 연산자와는 동작 방식 자체가 다릅니다!

리팩토링 해주셨으면 하는 부분 코멘트로 남겼습니다! 미션 정말 고생 많으셨고 앞으로도 파이팅!

2024-04-01 08:52 UTC, hangillee commented on docs/README.md
> +- [x] IllegalArgumentException을 따로 핸들링 하여 예외 메시지 출력
기능 구현 목록 작성 👍

2024-04-01 08:52 UTC, hangillee commented on src/main/java/baseball/service/BaseballGame.java
> +
불필요한 공백 라인 제거 해주세요~

2024-04-01 08:52 UTC, hangillee commented on src/main/java/baseball/service/BaseballGame.java
> +    private static final int RESTART_NO = 2;
매직 넘버 상수화 👍

2024-04-01 08:52 UTC, hangillee commented on src/main/java/baseball/model/Player.java
> +}
EOL에 대해서 학습해봅시다!

2024-04-01 08:52 UTC, hangillee commented on src/main/java/baseball/model/Player.java
> +        printInputMessage();
`Model`이 `View`를 알고 있습니다! MVC 패턴을 사용하는 이유가 없어져버린 것과 마찬가지인 상황이에요. 리팩토링 해볼까요? 힌트를 드리자면, `View`에서 입력받은 값을 `Model`로 넘겨줄 중간 계층이 필요합니다!

2024-04-01 08:52 UTC, hangillee commented on src/main/java/baseball/model/Player.java
> +        Validator.validateInputNumber(input);
마찬가지로 `Model`이 왜 입출력의 책임까지 지고 있나요? `Model`의 책임 범위는 비즈니스 로직까지입니다!

2024-04-01 08:52 UTC, hangillee commented on src/main/java/baseball/model/Player.java
> +    }
자연스럽게 이 메소드는 `Model`인 `Player`에 없어도 되겠죠?

2024-04-01 08:52 UTC, hangillee commented on src/main/java/baseball/service/BaseballGame.java
> +    public BaseballGame(Computer computer, Player player, CountResult countResult) {
이 객체는 역할만 보면 Controller에 가까운 것 같은데 `service` 패키지로 분류한 이유가 있을까요?

2024-04-01 08:52 UTC, hangillee commented on src/main/java/baseball/service/BaseballGame.java
> +    }
전반적인 메소드의 `indent`가 한 단계로 제한되어 깔끔한 것 같습니다. 읽기도 쉬웠어요! 👍

2024-04-01 08:52 UTC, hangillee commented on src/main/java/baseball/service/CountResult.java
> +            }
메소드로 분리할 수 있지 않을까요?

2024-04-01 08:52 UTC, hangillee commented on src/main/java/baseball/service/CountResult.java
> +                    .equals(computerNumbers.get(playerNumbers.indexOf(number)))) {
조건문이 어마무시하게 복잡한 것 같습니다. 메소드로 분리해서 의미를 부여해 봅시다.

2024-04-01 08:52 UTC, hangillee commented on src/main/java/baseball/service/CountResult.java
> +        int balls = 0;
여기서 발생하는 경고인 `Reassigned local variables`는 단순히 로컬 변수가 재할당 되었음을 경고하는 것입니다. 즉, 예기치 않은 부작용(side effect)를 방지하기 위함이니 해당 변수의 변화 이유를 명확하게 알고 있다면 크게 신경쓰지 않아도 좋습니다.

2024-04-01 08:52 UTC, hangillee commented on src/main/java/baseball/util/ErrorMessage.java
> +}
열거형 활용 👍

2024-04-01 08:52 UTC, hangillee commented on src/main/java/baseball/util/ExceptionHandler.java
> +        throw new IllegalArgumentException(errorMessage.message);
모든 예외가 잘못된 매개변수에 의해 발생했는지 한번 고려해볼만한 것 같습니다.

2024-04-01 08:52 UTC, hangillee commented on src/main/java/baseball/util/Validator.java
> +        }
각 `if`문들을 하나씩 메소드로 분리하고 이름을 부여한다면 주석이 필요 없어지지 않을까요? 주석은 해당 코드가 왜 그 위치에 있어야 하는지 설명할 때만 사용하는게 좋습니다. 주석을 없애봅시다.

2024-04-01 13:33 UTC, sojeong0202 commented
> 안녕하세요, 소정! 👋
> 
> 한번 해본 미션이지만 페어 프로그래밍이라는 익숙치 않은 방식으로 해결하느라 고생 많았습니다! 전반적으로 완성도 높은 코드였습니다. 느낀 점과 배운 점 적어주신 것도 인상 깊었어요!
> 
> 남겨주신 질문에 대한 답변입니다!
> 
> > 상대방에게 내 머릿속 코드(생각)를 잘 설명하기 힘들었다. 어떻게 하면 설명을 잘 할 수 있을까요?
> 
> 그래서 중요한게 코드 컨벤션입니다. 함께 합의한 코드 컨벤션이 잘 지켜졌다는 가정 하에 읽기 쉬운 코드(클린 코드)가 완성되었다면 당연히 코드만 읽고도 서로가 어떤 의도를 가졌는지 파악하기 쉽습니다.
> 
> > 이 주의 표시가 의미하는 바를 잘 모르겠습니다. Alt + Enter를 눌러도 뭔가 고치는 느낌이 안 들고 뭐지...? 이런 생각밖에 안 드는데 도대체 뭘까요?
> 
> 코멘트로 남겼습니다!
> 
> > 스트림에서 왜 [클래스 이름::메서드 이름] 이렇게 나타내는지 모르겠어요. [클래스 이름.메서드 이름] 이렇게 나타내면 되지 않나 싶은데... 이유가 있으니 이렇게 하는 거겠죠? 찾아봤는데 안 나오더라고요. (제대로 안 찾은 건가...)
> 
> Java Lambda 메소드 참조로 구글링 해보세요! `::`은 연산자로, `Stream`을 통해 넘어오는 각 `Stream` 요소들을 `::`을 통해 호출한 메소드의 매개변수로 **자동**으로 넘겨줍니다. 즉, Java의 연산자이며 `.`(도트) 연산자와는 동작 방식 자체가 다릅니다!
> 
> 리팩토링 해주셨으면 하는 부분 코멘트로 남겼습니다! 미션 정말 고생 많으셨고 앞으로도 파이팅!

정성스러운 코드 리뷰 감사합니다 🙇‍♀️ 급한 일들 해결하고 열심히 고쳐보겠습니다!!

2024-04-03 16:06 UTC, sojeong0202 commented
리뷰해주신 거 최대한 적용하려고 노력했습니다~

## 질문 1)
유효성 검사와 데이터 변환은 비즈니스 로직으로 보고 Model 안에서 처리하는 걸로 리팩토링 해봤는데 맞게 한 걸까요?

## 질문 2)
CountResult 클래스에서 countStrikes()와 countBalls() 메소드의 로직이 비슷해보여서 함수형 인터페이스, 람다식 이용할 수 있지 않을까 싶은데, 괜찮은 생각일까요? 
그리고 좀 어려워서😓 혹시 함수형 인터페이스 참고할 만한 글이 있으시다면 추천해주실 수 있을까요?
(없으면 안 해주셔도 됩니당~~)

## 질문 3)
발생할 수 있는 예외가 런타임 에러에서 또 있나요? 아니면 컴파일 에러나 다른 에러 범위를 말씀하시는 건가요? 
일단 잘 모르겠습니다, 힌트 조금만 주세요...!

---
+) CRLF를 다 LF로 바꾸고 커밋했는데(git에서도 true 바꿨는데) 어떤 거는 되고 어떤 거는 안 됐네요;; 왜 이러지... 더 찾아봐야겠습니다.

2024-04-04 07:19 UTC, hangillee approved these changes
안녕하세요, 소정! 👋

몇가지 코멘트를 더 남겼습니다. POSIX New Line에 대해서 학습해본 것 같군요!
코드 맨 마지막 줄은 공백 라인으로 두면 아마 모든 CRLF들이 사라질 겁니다.

남겨주신 질문들에 대한 답변입니다!
> 유효성 검사와 데이터 변환은 비즈니스 로직으로 보고 Model 안에서 처리하는 걸로 리팩토링 해봤는데 맞게 한 걸까요?

소정이 그게 맞다고 생각한다면 맞는 거겠죠? 스스로 그렇게 생각한 근거를 세우고 저뿐만 아니라 다른 개발자들을 설득하면 되는 겁니다. 일단 저는 크게 문제 없는 것 같습니다!

> CountResult 클래스에서 countStrikes()와 countBalls() 메소드의 로직이 비슷해보여서 함수형 인터페이스, 람다식 이용할 수 있지 않을까 싶은데, 괜찮은 생각일까요? 그리고 좀 어려워서😓 혹시 함수형 인터페이스 참고할 만한 글이 있으시다면 추천해주실 수 있을까요? (없으면 안 해주셔도 됩니당~~)

[☕ 함수형 인터페이스 표준 API 총정리](https://inpa.tistory.com/entry/%E2%98%95-%ED%95%A8%EC%88%98%ED%98%95-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4-API)

함수형 인터페이스 도입을 고려하고 계시는 군요! 시도해보는 걸 추천합니다. 왜 함수형 인터페이스를 사용하려 했는지, 사용했을 때 장단점은 무엇인지 명확한 소정만의 규칙도 세워봅시다.

> 발생할 수 있는 예외가 런타임 에러에서 또 있나요? 아니면 컴파일 에러나 다른 에러 범위를 말씀하시는 건가요? 일단 잘 모르겠습니다, 힌트 조금만 주세요...!

과연 모든 예외가 `IllegalArgumentException`일까요? 예외 클래스만으로도 어떤 상황에서 발생하는지 잘 알 수 있습니다. 한 번 고려해보세요!

이만하면 이번 미션에선 충분히 노력하신 것 같습니다! 제가 알려드린 내용, 학습하시기로 한 내용은 다음 미션에 적용해보세요! 숫자 야구 미션 고생하셨습니다!

2024-04-04 07:19 UTC, hangillee commented on src/main/java/baseball/model/Computer.java
> +        }
중복을 허용하지 않는 컬렉션이 있습니다. 학습해볼까요?

2024-04-04 07:19 UTC, hangillee commented on docs/README.md
> +진행하면서 페어프로그래밍의 재미를 느낄 수 있었습니다. 테스트 성공할 때 함께 소리 질렀습니다 😆
문서도 코드를 이해하는데 도움을 주는 엄연한 프로그램의 요소 중 하나입니다!
개인적인 후기나 생각은 문서에 적지 않는 것을 추천합니다. (블로그를 활용해봅시다!)

2024-04-04 07:19 UTC, merged