[숫자 야구 게임] 인상진 미션 제출합니다.
gdsc-skhu-pair-mission/java-baseball-6 pull request #4
Opened 2024-03-31 11:52 UTC by sangjin6439

2024-04-01 07:16 UTC, hangillee requested changes
안녕하세요, 상진! 👋
전반적으로 잘 동작하는 프로그램을 작성한 것 같습니다. 다만 몇가지 생각해볼만한 점들이 있는 것 같아 코멘트 남겼습니다. 확인 후 리팩토링 부탁드려요!

아래는 상진에게 묻고 싶은 것들입니다.
1. 우리가 Java를 통해 객체지향 프로그래밍을 하는 이유가 무엇일까요?
2. 이번 미션에서 객체지향 프로그래밍을 잘 했다고 생각하시나요? 그렇지 않다면 이유는 무엇인가요?
3. 코드 컨벤션을 지켜야 하는 이유는 무엇일까요?

스스로 위의 질문들에 대한 답을 찾아보고 저에게 알려주세요! 리팩토링도 파이팅입니다!

2024-04-01 07:16 UTC, hangillee commented on docs/README.md
구현 기능 목록 작성 👍

2024-04-01 07:16 UTC, hangillee commented on src/main/java/baseball/Application.java
> +        // 게임 실행
주석은 해당 코드가 어떤 일을 하는지 보다 왜 거기 있는지 설명하는데 사용하는 것이 좋습니다. 즉, 코드만 읽어도 무슨 일을 하는지 잘 알 수 있게 코드를 작성해야 합니다. 이 코드의 주석들은 지우는 게 나을 것 같습니다.

2024-04-01 07:16 UTC, hangillee commented on src/main/java/baseball/Application.java
> +        }
`while`의 조건이 `continueGame`이 될 수도 있을 것 같습니다. `while`문 내부에서 `continueGame`을 지속적으로 업데이트 하고 있으므로 굳이 `if`문으로 검사할 이유가 없습니다. 메소드의 `indent`(들여쓰기)를 줄이는 것도 클린 코드를 위해 꽤 중요한 항목입니다. 지금 당장은 클린 코드가 핵심 주제가 아니므로 이 부분을 리팩토링하는 것은 선택이지만, 웬만해선 메소드의 들여쓰기는 한 단계로 유지해보는 연습을 해봅시다.

2024-04-01 07:16 UTC, hangillee commented on src/main/java/baseball/Application.java
> +    public static String setting() {
`static`일 이유가 없는 메소드인 것 같습니다. 메소드가 `static`일 때의 단점을 한 번 학습해봅시다. 이렇게 `static` 사용해야했던 이유가 아마도 `Application.java` 파일에서 모든 동작을 처리해야 했기 때문인 것 같습니다. 즉, 클래스 분리의 신호입니다. 다음 리뷰 요청 때는 한번 리팩토링 해봅시다.

2024-04-01 07:16 UTC, hangillee commented on src/main/java/baseball/Application.java
> +        for (Integer num : computer) {
질문입니다.
Wrapper 클래스를 사용한 이유가 있나요?

2024-04-01 07:16 UTC, hangillee commented on src/main/java/baseball/Application.java
> +    public static boolean game(String computerNum) {
메소드의 길이가 너무 과도하게 깁니다. 즉, 한 메소드가 여러 역할과 책임을 가지고 있다는 이야기기도 합니다. 메소드 분리를 시도해봅시다.

2024-04-01 07:16 UTC, hangillee commented on src/main/java/baseball/Application.java
> +            }
이 부분은 충분히 메소드로 분리할 수 있지 않을까요?

2024-04-01 07:16 UTC, hangillee commented on src/main/java/baseball/Application.java
> +            }
이 부분 역시 위의 반복문과는 다른 역할(동작)을 수행하는 것 같습니다. 한 메소드가 하나의 동작만 하도록 리팩토링 해봅시다.

2024-04-02 00:57 UTC, sangjin6439 commented on src/main/java/baseball/Application.java
> +        for (Integer num : computer) {
사용이유: computer 리스트의 값이 Integer라서 Integer형으로 forEach 문을 사용했습니다. 
오토 박싱과 wrapper 클래스에 대해 다시 학습하여  int 형으로 forEach 문을 사용해도 자동형변환이 된다는 점을 알았습니다.

2024-04-02 05:24 UTC, hangillee commented on src/main/java/baseball/Application.java
> +        for (Integer num : computer) {
좋습니다! 사실 `Integer` 같은 Wrapper 클래스는 객체다보니 생성 과정에서 primitive type보다 리소스가 아주 조금 더 들어갑니다. 그래서 극한의 상황이 아닌 이상 별로 상관은 없지만 `Stream`에서 사용하는 것이 아니라면 primitive type을 활용합시다.

2024-04-02 06:53 UTC, hangillee requested changes

2024-04-02 06:53 UTC, hangillee commented on src/main/java/baseball/Application.java
> +}
EOL에 대해 학습해봅시다!

2024-04-03 07:46 UTC, sangjin6439 commented
1. 우리가 Java를 통해 객체지향 프로그래밍을 하는 이유가 무엇일까요?
여러 이유가 있겠지만 객체 지향적 설계를 통해 재사용성을 극대화하는 것이 중요하다고 생각합니다. 자바의 클래스, 객체, 메서드 등을 재사용하는 과정에서 개발 시간을 줄임과 동시에 확장성과 유지 보수성도 고려한다면 자바를 사용해 더욱 oop 적인 프로그래밍이 될 거 같습니다.

2. 이번 미션에서 객체지향 프로그래밍을 잘 했다고 생각하시나요? 그렇지 않다면 이유는 무엇인가요?
전혀 잘했다고 생각하지 않습니다. 처음 코드를 짤 때  한 클래스에 다 집어넣어서 프로그램을 짜야겠다는 생각을 하게 되었습니다.”한 클래스에 다 집어넣으면 클래스가 적어서 읽기 쉽겠지?”라는 생각을 했었습니다. 이러한 생각이 작동하는 쓰레기를 만들었고 oop 적인 관점을 생각하지 못하게 했습니다. 단순히 클래스가 적고 코드가 짧다고 해서 잘 짜인 코드가 아니라는 것을 깨닮았고, oop 적 코드를 짤 때에는 유지 보수, 재사용성, 확장성, 코드 간의 의존도 등등을 고려하며 짜야 한다는 것을 느꼈습니다.

3. 코드 컨벤션을 지켜야 하는 이유는 무엇일까요?
코드 컨벤션은 암묵적인 약속이라고 생각합니다. 왜 약속이 되었나 생각해 보면 소프트 웨어 개발 비용은 대부분 유지 보수에 쓰인다고 합니다. 그렇기에 코드 컨벤션을 지켜 코드가 이해하기 쉬워지고 가독성이 좋아지게 하여 개발 비용을 줄여야 합니다.   리팩토링 후 고친 점 주석을 왜 달아야 할까에 대해 더 고민했고 주석 없이도 이해할 수 있도록 코드를 짰습니다. 메서드에 한 역할만 담당하게 분리했고, 아무 생각 없이 썼던 static메서드에 대해 학습했고 왜 객체 지향적인 코드에서 static메서드를 지양하는지 학습했습니다. 클래스들 간의 의존도를 낮추려 했습니다. 초기 리팩토링에서 유저가 1을 입력하면 GameController 객체를 불러서 다시 실행하는 식으로 코드를 짰지만 객체에 대한 의존도를 낮추기 위해 statGame() 메서드로 나누고 메서드를 실행하는 식으로 객체 생성 시에 발생하는 추가적인 리소스 낭비를 줄였습니다. 

리팩토링 후 느낀 점 
한길님의 피드백 이외에도 같은 코드를 짠 페어의 피드백도 보고 최대한 맞춰가며 리팩토링과 테스트 코드 작성해 봤습니다. 처음 피드백을 받고 “객체지향적으로 코드를 짜야지”라고 마음먹고 리팩토링을 하고 나니 너무 어려웠습니다. 솔직히 지금의 코드도 최대한 메서드 나누고 책임을 하나씩 맡게 했지만 제 코드가 객체지향적으로 짜여 졌는지는 모르겠습니다.  의도적으로 “객체 지향적으로 짜야지” 보다는 습관이 되어서 내가 코드를 짰는데 이게 객체지향적이게 짜여진 수준까지는 너무 갈길이 멀다고 느꼈고, 아직은 oop 적인 관점에서 코드를 보는 눈이 낮아서 틀릴 수도 있기에 모두 받아들인다는 생각으로 피드백을 기다리고 있습니다!   다음 미션부터는 mvc 패턴을 적용할 것입니다.

 한길님께 질문! 
 1.EOL에 대해 학습해 보자고 했는데 End of Life를 말씀하신 거면 어떤 부분에서 말씀하신 걸까요? 
 2.제 코드를 보면 유저가 1을 누르면 startGame() 메서드를 호출해서 게임이 다시 시작하게 됩니다. 이 부분에서 재귀적인 호출이 쌓이게 되는데 너무 많은 재귀적인 호출이 쌓이면 스택오버 플로우와 같은 에러가 발생할 수 있는데 그렇게까지 신경을 안 써도 되는 부분인가요? 아니면 다른 방안이 있을까요?  

2024-04-04 05:40 UTC, hangillee approved these changes
안녕하세요 상진! 👋
열심히 고민해 본 흔적이 보이네요!

제가 드린 질문에 대한 답변도 잘 읽어봤습니다. 저는 객체지향 프로그래밍에 정답은 없지만 오답은 있다고 생각합니다. 잘못된 개발 방법을 사용하면 코드가 작성되는 순간 유지보수하기 어려워집니다. 도메인 지식이 많이 쌓인게 아닌 이상 처음부터 객체 분리를 하긴 어렵습니다. (Out - In, In - Out 방식에 대해 학습해봅시다.) 꾸준히 경험을 쌓고 많이 해보는 수 밖엔 없습니다. 🙂

남겨주신 질문에 대한 답변입니다!
> EOL에 대해 학습해 보자고 했는데 End of Life를 말씀하신 거면 어떤 부분에서 말씀하신 걸까요?

`End of Line`입니다! POSIX New Line에 대해서 학습해보시면 될 겁니다. Files changed 탭에서 코드를 확인하시면 가끔 빨간색 금지 표시가 코드 끝에 있는 걸 확인할 수 있는데 이는 별로 추천되지 않습니다.

> 제 코드를 보면 유저가 1을 누르면 startGame() 메서드를 호출해서 게임이 다시 시작하게 됩니다. 이 부분에서 재귀적인 호출이 쌓이게 되는데 너무 많은 재귀적인 호출이 쌓이면 스택오버 플로우와 같은 에러가 발생할 수 있는데 그렇게까지 신경을 안 써도 되는 부분인가요? 아니면 다른 방안이 있을까요?

당연히 `StackOverflowException` 발생 가능성이 높습니다. `while`문으로 대체하는 건 어떨까요? 확실한 종료 조건이 있는 것이 더 낫습니다. 재귀는 정말 제한적으로 다뤄야하는 위험한 친구입니다.

조금 더 수정해볼만한 부분들이 있지만, 다음 미션에서 반영해도 충분할 것 같다는 생각이 들어 `merge`하려 합니다! 미션 고생하셨습니다!

2024-04-04 05:40 UTC, hangillee commented on src/main/java/baseball/GameController.java
> +    public String createComputerNum() {
주석은 제거해주세요. 메소드 이름만으로 충분히 알 수 있을 것 같습니다.

2024-04-04 05:40 UTC, hangillee commented on src/main/java/baseball/GameController.java
> +        System.out.println("숫자 야구 게임을 시작합니다.");
출력은 View의 역할이자 책임인 것 같습니다. View 계층을 분리할 때가 된 것 같습니다.

2024-04-04 05:40 UTC, hangillee commented on src/main/java/baseball/GameController.java
> +            }
`gameContinue`가 `while` 외부에서 선언되고 `while`의 조건이 된다면 `if`문이 필요 없지 않을까요? 🤔

2024-04-04 05:40 UTC, hangillee commented on src/main/java/baseball/GameController.java
> +    }
이 로직은 Controller가 갖기에는 너무 핵심 비즈니스 로직에 가까운 것 같습니다. 객체를 설계할 때 역할과 책임을 잘 고려해봅시다!

2024-04-04 05:40 UTC, hangillee commented on src/main/java/baseball/GameController.java
> +    }
이 로직도 마찬가지!

2024-04-04 05:40 UTC, hangillee commented on src/test/java/baseball/BaseBallGameTest.java
> +
불필요한 공백 제거

2024-04-04 05:40 UTC, merged