[숫자 야구 게임] 김동균 미션 제출합니다.
gdsc-skhu-pair-mission/java-baseball-6 pull request #6
Opened 2024-03-31 14:26 UTC by dongkyun0713

### 어려웠던 점
* 페어가 작성했던 코드에 이어서 코드를 작성하는 것이 어려웠습니다.

### 궁금한 점
* 현재 코드에서 테스트 코드를 짜려고 시도했지만, 구현에 있어서 어려움을 느끼고 결국 포기했습니다.  테스트 코드를 짠다면 어떤식으로 짤 수 있을까요?
* 현재 코드가 mvc패턴을 잘 지켰는지 궁금합니다.
* 현재 코드의 문제점이 있다면 어디가 잘못됐는지 궁금합니다.

2024-03-31 15:08 UTC, HanHyunsoo requested changes
## 느낀점
* MVC로 각각의 역할을 분리한 것에 칭찬해드리고 싶어요. 하지만 자세히 들여다보면 서로 역할을 침범한 경우(ex - View가 사용자의 입력을 받는 것)가 있네요. 이 부분에 대해서 고민해보고 수정하면 좋을 것 같아요.
* 각 코드 별로 수정하면 좋을 점, 개선하는 방향에 대해 적어놨으니 읽어보시고 리팩토링 하시면 될 것 같습니다. 
* 여담이지만 저 또한 개발자를 꿈꾸는 학생으로서 부족한 점 & 틀린점이 있을 수 있어요 감안해서 들어주시구 잘못 설명한 부분이 있다면 저에게 피드백 해주시면 좋을 것 같습니다 :)

## 궁금한 점에 대한 답변
* 현재 코드에서 테스트 코드를 짜려고 시도했지만, 구현에 있어서 어려움을 느끼고 결국 포기했습니다.  테스트 코드를 짠다면 어떤식으로 짤 수 있을까요?
  * 각 도메인(컴퓨터, 유저) 별로 다시한번 DAO(repository), BO(Service)로 나누면 테스트하기 편할 것 같아요. 레이어로 생각하면 Domain(model) - DAO - BO - Controller - View
  * 위와 같이 구성하면 DAO - BO - View 별로 단위 테스트 하면 되겠지요?
  * 단위 테스트를 모른다면 JUnit, Mockito에 대해 공부해보기!
* 현재 코드가 mvc패턴을 잘 지켰는지 궁금합니다.
  * 아쉬운점은 분명 있지만 리팩토링하면 괜찮아 질 것 같아요.
* 현재 코드의 문제점이 있다면 어디가 잘못됐는지 궁금합니다.
  * 문제점 & 개선점은 코드 라인마다 댓글로 써놨으니 확인하면 되실듯합니다.
  
그 외로 궁금한 부분 언제든지 환영해요~~

2024-03-31 15:08 UTC, HanHyunsoo commented on src/main/java/baseball/model/Computer.java
> +    public void setComputerNumbers(List<Integer> computerNumbers) {
SOLID 원칙중 O에 해당하는 '개방 폐쇄 원칙'을 생각하면 좋을 것 같아요.

만약 개발자가 의도치않게 set함수로 기존 컴퓨터 숫자들을 바꾸게되면?.. 클래스 변수의 일관성이 떨어지지않을까요?

꼭 set함수로 변수를 초기화해야할까요? 변수의 기본값을 초기화하기 위해서 setter대신에 다른 방안을 고려해보시면 좋을 것 같아요

2024-03-31 15:08 UTC, HanHyunsoo commented on src/main/java/baseball/model/User.java
> +    public void setNumbers(List<Integer> numbers) {
이것도 Computer setter와 동일하게 보면 될 것 같습니다.

2024-03-31 15:08 UTC, HanHyunsoo commented on src/main/java/baseball/view/GameView.java
> +    public String InputNumbers() {
~~View의 역할은 사용자에게 보여지는 부분. 즉 출력하는 역할을 해요~~

~~근데 Controller의 입력 역할을 View에 하니까 조금 애매한 부분이 있는 것 같아요.~~

~~입력의 책임을 Controller에 넘기는 것을 한번 고려해보세요.~~

2024-03-31 15:08 UTC, HanHyunsoo commented on src/main/java/baseball/exception/ErrorMessage.java
> +public class ErrorMessage {
ErrorMessage를 상수 형태로 표현한 것은 좋은 것 같아요.

하지만 해당 클래스를 Enum 클래스로 변경하여 좀 더 역할에 맞는 클래스로 만들 수 있을 것같아요. 한번 리팩토링 해보세요~

2024-03-31 15:08 UTC, HanHyunsoo commented on src/main/java/baseball/controller/NumberBaseballGameController.java
> +    private final GameView gameview = new GameView();
컨트롤러가 모델들과 View를 이어주고 제어하는 역할로 잘 구분하신 것 같아요.

하지만 만약에 NumberBaseballGameController의 인스턴스가 여러개라면 View, Model도 여러개 생성될 것 같아 메모리적으로도, 객체 일관성으로도 떨어지는 부분이 있을 것 같아요.

해당 코드를 보면 객체간의 결합도가 높아보이는데 낮출 수 있는 방법을 고민해보세요(hint: 생성자, 스프링에서 객체를 싱글톤으로 이용하는 방법)

2024-03-31 15:08 UTC, HanHyunsoo commented on src/main/java/baseball/controller/NumberBaseballGameController.java
> +            if (!computerNumbers.contains(randomNumber)) {
Collection에 contains로 중복을 검사하는 로직을 좀 더 개선할 수 있을 것 같아요.

만약 computerNumbers에 값이 무수히 많게 되면 특정 값을 찾기위해서 최악의 경우 O(N)의 시간이 걸릴 수도 있어요.

O(1)로 줄일 수 있을 것 같은데 그에 해당하는 자료구조 방식을 사용하면 좋을 것 같습니다.

2024-03-31 15:08 UTC, HanHyunsoo commented on src/main/java/baseball/controller/NumberBaseballGameController.java
> +    private boolean isDistinct(String input) {
만약 input의 length가 무수히 많다면 O(N)이 걸리는데 O(1) 방법으로 고려해보세요

2024-03-31 15:08 UTC, HanHyunsoo commented on src/main/java/baseball/controller/NumberBaseballGameController.java
> +            if (computerNumbers.contains(userNumbers.get(i))) {
이것도 O(1)로 변경할 수 있을 것 같습니다!

2024-03-31 15:08 UTC, HanHyunsoo commented on src/main/java/baseball/controller/NumberBaseballGameController.java
> +            } if (Objects.equals(computerNumbers.get(i), userNumbers.get(i))) {
해당 코드만 보고 어떤 타입이 같은지 명확하게 보이지 않네요. 위 부분을 봐야 Integer 변수끼리 같은지 확인할 수 있어요.

다른 메서드를 고려해보시면 좋을 것 같아요.

2024-04-02 06:56 UTC, dongkyun0713 commented on src/main/java/baseball/view/GameView.java
> +    public String InputNumbers() {
제가 알기로는 view에서 사용자의 입력을 컨트롤러에 전달하는 것으로 알 고 있는데, 잘못된 지식인가요?

2024-04-02 07:17 UTC, HanHyunsoo commented on src/main/java/baseball/view/GameView.java
> +    public String InputNumbers() {
> 제가 알기로는 view에서 사용자의 입력을 컨트롤러에 전달하는 것으로 알고 있는데, 잘못된 지식인가요?

그 부분에 대해서 따로 찾아보고 공부를 진행했는데 동균님 말씀이 맞는 것 같습니다. 저는 입력은 Controller, 출력은 View에만 해당되는 줄 알았는데 아래 링크에서는 View에서 입출력을 관리할 수 있다고 말하네요.

* [MVC](https://developer.mozilla.org/ko/docs/Glossary/MVC)

2024-04-02 17:28 UTC, dongkyun0713 commented on src/main/java/baseball/controller/NumberBaseballGameController.java
> +    private boolean isDistinct(String input) {
이 부분에서 O(N)이 어떻게 나오는지 이해가 안됩니다.. 
length가 무수히 많아도 앞에 3글자만 비교해지는 것 아닌가요??

2024-04-03 04:28 UTC, HanHyunsoo commented on src/main/java/baseball/controller/NumberBaseballGameController.java
> +    private boolean isDistinct(String input) {
> 이 부분에서 O(N)이 어떻게 나오는지 이해가 안됩니다.. length가 무수히 많아도 앞에 3글자만 비교해지는 것 아닌가요??

동균님 말씀이 맞습니다. 하지만 3개만 비교하는 로직이기 때문에 O(1)의 시간이 걸리지만 input의 길이가 그만큼 길어진다면 모든 값들을 비교해야하는 로직을 만들어야해서 O(N)이 걸린다고 저는 생각했어요 혼동드려서 죄송해요 ㅎ. O(1)을 만족하면서 가변적인 input의 길이를 모두 비교하는 방법을 고려해보시라는 뜻이였습니다.

2024-04-03 04:30 UTC, dongkyun0713 commented on src/main/java/baseball/controller/NumberBaseballGameController.java
> +    private boolean isDistinct(String input) {
아하, 이해했습니다!! 다시 한번 생각해보고 리펙토링 해보겠습니다!

2024-04-03 17:21 UTC, HanHyunsoo requested changes
### 리팩토링 한 경위에 대한 답변

* 먼저 NumberBaseballGameController에서 생성자를 통해 객체를 생성하여, 객체의 인스턴스가 오직 1개만 생성되도록 해보았습니다. 또한 인터페이스를 활용하여 객체간의 결합도를 낮춰보았습니다.
  * Controller가 싱글턴 패턴으로 운영되는것은 인지했지만 GameView, ComputerRandomNumber, 그리고 Input이 싱글턴 패턴은 아닌 것 같아요. 스프링에서 DI를 하기위한 방법중 생성자 주입 방식이 있는데 인사이트를 얻어서 다시 고치면 좋을 것 같아요.
  * 인터페이스를 쓸 필요는 없는 것같아요. Computer와 Input의 역할을 더 사용하는 클래스는 없기 때문이라고 생각해요. 예시를 들께요. 총이라는 클래스(or 인터페이스)가 있다면 권총, 소총으로 상속받아 다른 클래스를 만들 수 있겠죠? 하지만 해당 Input과 Computer를 봤을 때 예시에 들었던 권총, 소총에 속하는거같아요. 즉 인터페이스로 나눌 필요가 없다(= 해당 인터페이스는 상속 or 구현의 의미가 없는 것 같다.)라고 생각합니다.
* 랜덤 숫자 생성의 책임을 모델 객체인 ComputerRandomNumber에게 돌렸습니다. 그렇게 한 이유는 랜덤 숫자 생성은 컴퓨터에서 하는 것이기 떄문에, 굳이 컨트롤러에서 생성을 하지 않아도 된다고 생각이 들어서 ComputerRandomNumber에서 생성하여 컨트롤러에 전달하도록 했습니다. 또한 중복 검사 로직을 Set을 활용하여 검사하는데 있어서 더 효율성을 높였습니다.
  * 관점에 따라 다르겠지만 Controller, Model 둘 중에 하나에 위임해도 될거같아요. 개인적인 생각으로 게임을 시작하면 random 값을 변경이 안되기 때문에 Model에 해도 괜찮을 것 같아요.
  * Set 사용 굳
* 데이터 처리 및 유효성 검사를 model에서 하는 것이 더 바람직하다고 생각되어 예외처리를 모델에서 하도록 변경하였습니다. 
  * 이것도 관점의 차이이긴하지만 저같은 경우 입력단에서 검증, Model에서 다시한번 검증하는 것을 선호해요.
* 객체의 일관성을 유지하기 힘든 Setter 대신 생성자를 활용하여 update를 했습니다.
  * 굳 Setter를 사용하지 말라는 의미 보단 지양의 의미로 받아드리면 좋을 것 같아요.
* ErrorMessage를 Enum을 활용하여 타입 안정성을 높였습니다.
  * 굳굳
* 테스트 코드는 공부 후 해보겠습니다!!
  * 굳

## 리펙토링 후 궁금한 점에 대한 답변
* Setter대신  this.userInputNumber = new UserInputNumber(input);로  변수를 초기화 하였는데요. 이렇게 하면 입력받을 때마다 객체를 생성하여 비효율적이라는 생각이 들었습니다. 혹시 더 좋은 방법이 있다면 어떤 것이 있을 까요?
  * 그 경우에는 setter를 사용해도 무방할 것 같아요. 오히려 무분별하게 객체가 생성된다면 GC가 발동하기 때문에 비효율적이라고 생각해요. 해당 객체 내부에있는 값만 변경하면 될 것 같습니다.
* isDistinct() 메소드에서 O(1)을 만족하면서 가변적인 input의 길이를 모두 비교하는 방법으로 Set을 활용한 중복 검사를 떠올려 봤었습니다. 하지만 입력문을 Set에 삽입하는 시간과 사이즈를 반환하는 시간이 현재 제 로직보다 비효율적이라 판단되어서 수정을 멈췄습니다. 그런데 앞에서 글자 수가 3이 아니면 예외처리를 하는데 굳이 lengh가 무수히 많을 때를 생각해야 하는지에 대한 의문이 들었습니다. 혹시 더 좋은 방법이 있다면 어떤 걸까요?
  * 제가 의도한 방식을 생각하셨군요 잘하셨습니다 ㅎㅎㅎ. 굳이 length가 정해져있고 앞에서 예외처리를 하는데 무수히 많은 경우를 생각해야하는가에 대한 답변은 정답은 없습니다. 동균님 생각대로 구현해야하는 스펙이 3개로 정해져있다면 기존 방식대로 가셔도 되요. 하지만 제 답변의 의도는 다양한 시각에서 바라보는 점에서 말씀 드린점이에요. 단순히 기능을 구현하는 것을 넘어서 문제를 가정하면 더 넓은 시야를 가질 수 있어요. 3개가 아니라 10000개라면? 1000000개라면? 어떻게 처리하지? 이런 고민들이 더 성장할 수 있는 계기가 된다 생각해요.

### 전체적인 느낀점

* 기존 코드를 잘만드셔서 바뀐점이 많이 없네요 칭찬드립니다!
* 아래 두개 부분만 리팩토링 하시면 완벽할 것 같습니다.
  * GameController에서 클래스 변수들을 싱글톤으로 관리하기(hint: 생성자 주입) 정답에 가깝게 리팩토링 했지만 아쉬운 부분이 있어요 좀만 더 고민해보고 수정해보세요!
  * 인터페이스를 분리한 목적이 이해되지 않습니다. 공통으로 쓰이는 클래스들이 안보여서 그런 것 같아요. 이전 코드 베이스로 가시는게 괜찮을 것 같습니다.

2024-04-03 17:21 UTC, HanHyunsoo commented on src/main/java/baseball/controller/NumberBaseballGameController.java
> +    private final View gameview;
객체의 변수가 정해지지 않고 생성자로 주입하는 것으로 리팩토링 했군요 굳굳

하지만 해당 코드를 봤을때 GameView, ComputerRandomNumber, Input이 싱글톤 패턴인지 의문이 드네요 GameController를 빈 생성자로 여러개 생성한다면 내부 변수 도 여러개 생성되지 않을까요?

해당 변수들을 싱글톤 패턴으로 사용하기 위해 고민을 해봤으면 좋겠어요(hint: 생성자)

2024-04-04 07:02 UTC, dongkyun0713 commented
## 2차 리펙토링
### 리펙토링 경위
* 먼저 GameView, ComputerRandomNumber, Input를 싱글톤 패턴을 적용하여 객체 생성이 한번만 이루어지도록 변경하였습니다.
* 인터페이스를 제거하였습니다.
* 무분별한 GC발생을 막기 위해 set으로 입력 번호를 초기화하도록 하였습니다.
* ComputerRandomNumber보다는 Computer라는 모델이 더 직관적이라 클래스 이름을 변경하였습니다.
---
### 궁금한 점
* 제가 이해한대로라면 싱글톤 패턴을 잘 적용시킨 것 같습니다. 혹시 틀렸다면 어디가 문제일까요?
* 싱글톤 패턴을 GameView, Computer, Input 변수에만 적용 시켰는데 NumberBaseballGameController는 게임이 새로 시작될때마다 객체를 새로 생성하는게 맞다고 생각되어 따로 getInstance() 메소드를 만들어 적용시키지 않았습니다. 이게 올바른 생각인가요?
---
### 느낀점
* 사실 싱글톤 패턴이라는 개념에 대해서 머리로는 알고 있었지만, 이것을 왜 적용시켜야 하고 적용시켰을 때 어떤 장점이 있는지는 깨닫지 못하고 있었습니다. 이번 기회를 통해 싱글톤 패턴의 개념에 대한 정리가 된 것 같습니다.
* 인터페이스를 사용하면 객체간의 결합도를 낮출 수 있을 거란 생각에 무지성으로 넣었지만, 공통으로 쓰이는 클래스가 없어서 굳이 필요하지 않다는 점을 느꼈습니다.
* 이번 기회에 많은 것을 배우고 또 느낀 것 같습니다!  감사합니다!

2024-04-04 15:47 UTC, dongkyun0713 commented on src/main/java/baseball/controller/NumberBaseballGameController.java
> +    private final View gameview;
참고해서 리펙토링 했습니다!

2024-04-05 05:27 UTC, HanHyunsoo approved these changes
제가 생각한 의도보다 더 좋은 싱글턴 방안을 사용하셨네요 고생하셨습니다.

제 의도는 스프링에서 생성자 주입으로 의존성 주입을 시키는 것을 말한 것이였지만 이게 가능한 이유는 스프링 IOC로 객체를 싱글턴으로 관리하기 때문입니다.

하지만 그냥 java는 그런 ioc 개념이 없으니까 동균님 방식대로 jvm 단에서 관리하는 방식도 되게 좋은 것 같아요 칭찬드립니다!!

2024-04-05 05:28 UTC, merged